#!/usr/bin/env python

import argparse
import os

def process(path):
    os.chmod(path, os.stat(path).st_mode & 0o777666)

def process_batch(root, names):
    for name in names:
        process(os.path.join(root, name))

def process_all(dir):
    for root, dirnames, filenames in os.walk(dir, topdown = False):
        process_batch(root, filenames)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description = 'Remove executable permission recursively')
    parser.add_argument('path', help = 'path to the directory to start from')
    args = parser.parse_args()
    process_all(args.path)
